[package]
name = "c2rust-refactor"
version = "0.11.0"
authors = [
  "The C2Rust Project Developers <c2rust@immunant.com>",
  "Stuart Pernsteiner <spernsteiner@galois.com>",
]
build = "build.rs"
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
description = "C2Rust refactoring tool implementation"
edition = "2018"

[dependencies]
diff = "0.1.10"
json = "0.11.8"
libc = "0.2.28"
regex = "1.1.0"
ena = "0.13"
c2rust-ast-builder = { version = "0.11.0", path = "../c2rust-ast-builder" }
indexmap = { version = "1.0.1", features = ["serde-1"] }
cargo = "0.34.0"
clap = {version = "2.33", features = ["yaml"]}
env_logger = "0.6"
log = "0.4"
rlua = "0.16.3"
slotmap = {version = "0.3", features = ["unstable"]}
derive_more = "0.14"
c2rust-macros = { version = "0.11.0", path = "../c2rust-macros" }
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.3", optional = true }
c2rustc_mir = { path = "./dependencies/librustc_mir" }
# polonius-engine = { path = "./src/polonius-engine" }

[lib]
name = "c2rust_refactor"
path = "src/lib.rs"

[features]
default = []
profile = ["flame", "flamer"]
